# Generated by Django 4.2 on 2025-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_way_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('exp_date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=4)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
