# Generated by Django 4.2 on 2025-11-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_way_application', '0003_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='united_way_application.claim'),
        ),
    ]
